"""Added new fields to Book model

Revision ID: 382c1adb90e6
Revises: dbeaa77218be
Create Date: 2025-03-23 10:11:20.519720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382c1adb90e6'
down_revision = 'dbeaa77218be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('is_available')
        batch_op.drop_column('author')

    # ### end Alembic commands ###
